### ISSUE TITLE
Make dev install work for everyone.

### ISSUE THREAD

**Issue by Carreau** [Carreau/papyri#14]
There are many places in the code that assume it's running on my machine, or might make assumptions that folders/files already exist. 

It would be nice to have the basic workflow work for everyone. 

# install papyri

```
$ pip install flit
$ git clone https://github.com/Carreau/papyri
$ cd papyri
$ flit install --symlink
$ git clone https://github.com/stsewd/tree-sitter-rst
$ papyri build-parser
```

# Create own docs:

```
$ papyri gen examples/papyri.toml
$ papyri ingest ~/.papyri/data/papyri_0.0.8/
```

# View own docs

```
$ papyri serve
Running on http://127.0.0.1:5000 (CTRL + C to quit)
```

**Comment by Carreau** [comment]
@jasongrout I've reworked the readme, and rechecked the it should work from a clean environment.
The above instruction should be the strict minimal to make sure papyri works. Do you want to give it a shot ?

**Comment by jasongrout** [comment]
Trying to build the parser, I get:

```
% papyri build-parser
Traceback (most recent call last):
  File "/[snip]/bin/papyri", line 8, in <module>
    sys.exit(main())
  File "/[snip]/lib/python3.9/site-packages/papyri/__init__.py", line 169, in main
    app()
  File "/[snip]/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/[snip]/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/[snip]/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/[snip]/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/[snip]/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/[snip]/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/[snip]/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/[snip]/lib/python3.9/site-packages/papyri/__init__.py", line 359, in build_parser
    from tree_sitter import Language, Parser
ModuleNotFoundError: No module named 'tree_sitter'
```

DId you install the tree_sitter package too, not just clone it?

**Comment by jasongrout** [comment]
Looks like it works if I do `pip install tree_sitter`

**Comment by Carreau** [comment]
Great ! Added to requirement.txt and pyproject_toml, not sure why it does work in an env for me without installing it. I liekly screwed something up.

**Comment by jasongrout** [comment]
> `$ papyri gen examples/papyri.toml`

For this, I also had to install `matplotlib`

**Comment by melissawm** [comment]
It looks like the instructions now are more general - I was able to set up a dev install following the instructions. Should this be closed?
